// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARRtMSoCJb4wrTy5dEkOUJFiX0fpct5PE',
    appId: '1:438320612271:web:68074ea46fb84f1b2e255a',
    messagingSenderId: '438320612271',
    projectId: 'raksha-11563',
    authDomain: 'raksha-11563.firebaseapp.com',
    storageBucket: 'raksha-11563.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkKc2jjD2DfCMccICGvmYAh3kZBiGe_dE',
    appId: '1:438320612271:android:cd592d1810fab3722e255a',
    messagingSenderId: '438320612271',
    projectId: 'raksha-11563',
    storageBucket: 'raksha-11563.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKZyFNR8s02JmeZ4quml_R8xeTF3Ilbjs',
    appId: '1:438320612271:ios:82aafd42096c61562e255a',
    messagingSenderId: '438320612271',
    projectId: 'raksha-11563',
    storageBucket: 'raksha-11563.firebasestorage.app',
    iosBundleId: 'com.example.raksha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKZyFNR8s02JmeZ4quml_R8xeTF3Ilbjs',
    appId: '1:438320612271:ios:82aafd42096c61562e255a',
    messagingSenderId: '438320612271',
    projectId: 'raksha-11563',
    storageBucket: 'raksha-11563.firebasestorage.app',
    iosBundleId: 'com.example.raksha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARRtMSoCJb4wrTy5dEkOUJFiX0fpct5PE',
    appId: '1:438320612271:web:598d05e77e6263e82e255a',
    messagingSenderId: '438320612271',
    projectId: 'raksha-11563',
    authDomain: 'raksha-11563.firebaseapp.com',
    storageBucket: 'raksha-11563.firebasestorage.app',
  );
}
